sudo: required
services:
  - docker


before_install:
  - docker build -t khalidshaheen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run khalidshaheen/react-test npm test -- --coverage

after_success:
  - docker build -t khalidshaheen/multi-client ./client
  - docker build -t khalidshaheen/multi-nginx ./nginx
  - docker build -t khalidshaheen/multi-server ./server
  - docker build -t khalidshaheen/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push khalidshaheen/multi-client
  - docker push khalidshaheen/multi-nginx
  - docker push khalidshaheen/multi-server
  - docker push khalidshaheen/multi-worker
  
  # Test